// SETTINGS
// LOCALIZATION
export const CHANGE_SETTINGS_LOCALIZATION = 'CHANGE_SETTINGS_LOCALIZATION';
export const CHANGE_SETTINGS_LOCALIZATION_IS_ALLOWED = 'CHANGE_SETTINGS_LOCALIZATION_IS_ALLOWED';
// TYPING FORM
export const TYPING_USERNAME_CHANGED = 'TYPING_USERNAME_CHANGED';
export const TYPING_PASSWORD_CHANGED = 'TYPING_PASSWORD_CHANGED';

// STATUS
export const STATUS_LOADING = 'STATUS_LOADING';
export const STATUS_GLOABL_RESPONSE_SUCCESS = 'STATUS_GLOABL_RESPONSE_SUCCESS';
export const STATUS_GLOABL_RESPONSE_FAILED = 'STATUS_GLOABL_RESPONSE_FAILED';
export const STATUS_LOGIN_SUCCESS = 'STATUS_LOGIN_SUCCESS';
export const STATUS_LOGIN_FAILED = 'STATUS_LOGIN_FAILED';
export const STATUS_GET_PHONE_EXT_SUCCESS = 'STATUS_GET_PHONE_EXT_SUCCESS';
export const STATUS_GET_PHONE_EXT_FAILED = 'STATUS_GET_PHONE_EXT_FAILED';
export const STATUS_GET_COUNTRY_OPTIONS_SUCCESS = 'STATUS_GET_COUNTRY_OPTIONS_SUCCESS';
export const STATUS_GET_COUNTRY_OPTIONS_FAILED = 'STATUS_GET_COUNTRY_OPTIONS_FAILED';
export const STATUS_GET_STATE_OPTIONS_SUCCESS = 'STATUS_GET_STATE_OPTIONS_SUCCESS';
export const STATUS_GET_STATE_OPTIONS_FAILED = 'STATUS_GET_STATE_OPTIONS_FAILED';
export const STATUS_GET_AREA_OPTIONS_SUCCESS = 'STATUS_GET_AREA_OPTIONS_SUCCESS';
export const STATUS_GET_AREA_OPTIONS_FAILED = 'STATUS_GET_AREA_OPTIONS_FAILED';

// TOKEN TOKEN_MANAGER
export const TOKEN_MANAGER_CHECK_LOGIN = 'TOKEN_MANAGER_CHECK_LOGIN';
export const TOKEN_MANAGER_GET_TOKEN = 'TOKEN_MANAGER_GET_TOKEN';

// GET APPLICATION OPTIONS
export const GET_APP_PHONE_EXT_OPTIONS = 'GET_APP_PHONE_EXT_OPTIONS';
export const GET_APP_COUNTRY_OPTIONS = 'GET_APP_COUNTRY_OPTIONS';
export const GET_APP_STATE_OPTIONS = 'GET_APP_STATE_OPTIONS';
export const GET_APP_AREA_OPTOPNS = 'GET_APP_AREA_OPTOPNS';

// SELECT APPLICATION OPTIONS
export const SELECT_APPLICATION_CLEAR_OPTIONS = 'SELECT_APPLICATION_CLEAR_OPTIONS';
export const SELECT_APPLICATION_PHONE_EXT_OPTIONS = 'SELECT_APPLICATION_PHONE_EXT_OPTIONS';
export const SELECT_APPLICATION_COUNTRY_OPTIONS = 'SELECT_APPLICATION_COUNTRY_OPTIONS';
export const SELECT_APPLICATION_STATE_OPTIONS = 'SELECT_APPLICATION_STATE_OPTIONS';
export const SELECT_APPLICATION_AREA_OPTIONS = 'SELECT_APPLICATION_AREA_OPTIONS';

// SELECT MERCHANT FILTER OPTIONS
export const SELECT_MERCHANT_FILTER_COUNTRY_OPTIONS = 'SELECT_MERCHANT_FILTER_COUNTRY_OPTIONS';
export const SELECT_MERCHANT_FILTER_STATE_OPTIONS = 'SELECT_MERCHANT_FILTER_STATE_OPTIONS';
export const SELECT_MERCHANT_FILTER_AREA_OPTIONS = 'SELECT_MERCHANT_FILTER_AREA_OPTIONS';
export const SELECT_MERCHANT_FILTER_NOB_OPTIONS = 'SELECT_MERCHANT_FILTER_NOB_OPTIONS';

// SELECT USER PROFILE UPDATE OPTIONS
export const SELECT_USER_PROFILE_COUNTRY_OPTIONS = 'SELECT_USER_PROFILE_COUNTRY_OPTIONS';
export const SELECT_USER_PROFILE_STATE_OPTIONS = 'SELECT_USER_PROFILE_STATE_OPTIONS';
export const SELECT_USER_PROFILE_AREA_OPTIONS = 'SELECT_USER_PROFILE_AREA_OPTIONS';
export const SELECT_USER_PROFILE_PHONE_EXT_OPTIONS = 'SELECT_USER_PROFILE_PHONE_EXT_OPTIONS';

// FORM UPDATE
export const FORM_USER_ISREFRESHING = 'FORM_USER_ISREFRESHING';
export const FORM_USER_CLEAR_ALL = 'FORM_USER_CLEAR_ALL';
export const FORM_USER_REGISTER = 'FORM_USER_REGISTER';
export const FORM_MERCHANT_FILTER = 'FORM_MERCHANT_FILTER';
export const FORM_USER_UPDATE = 'FORM_USER_UPDATE';

export const FORM_GLOBAL_ACTION_UPDATE = 'FORM_GLOBAL_ACTION_UPDATE';
export const FORM_GLOBAL_ACTION_CLEAR = 'FORM_GLOBAL_ACTION_CLEAR';
export const FORM_GLOBAL_ACTION_USERNAME_SUCCESS_CLEAR = 'FORM_GLOBAL_ACTION_USERNAME_SUCCESS_CLEAR';
export const FORM_GLOBAL_ACTION_REFRESH = 'FORM_GLOBAL_ACTION_REFRESH';
export const SELECT_GLOBAL_FORMS_COUNTRY_OPTIONS = 'SELECT_GLOBAL_FORMS_COUNTRY_OPTIONS';
export const SELECT_GLOBAL_FORMS_STATE_OPTIONS = 'SELECT_GLOBAL_FORMS_STATE_OPTIONS';
export const SELECT_GLOBAL_FORMS_AREA_OPTIONS = 'SELECT_GLOBAL_FORMS_AREA_OPTIONS';
export const SELECT_GLOBAL_FORMS_PHONE_EXT_OPTIONS = 'SELECT_GLOBAL_FORMS_PHONE_EXT_OPTIONS';
export const SELECT_GLOBAL_FORMS_NOB_OPTIONS = 'SELECT_GLOBAL_FORMS_NOB_OPTIONS';
export const SELECT_GLOBAL_FORMS_MERCHANT_GROUP_OPTIONS = 'SELECT_GLOBAL_FORMS_MERCHANT_GROUP_OPTIONS';
export const SELECT_GLOBAL_FORMS_BANK_OPTIONS = 'SELECT_GLOBAL_FORMS_BANK_OPTIONS';
export const SELECT_GLOBAL_FORMS_COMP_BANK_OPTIONS = 'SELECT_GLOBAL_FORMS_COMP_BANK_OPTIONS';
export const FORM_GLOBAL_ACTION_TARGET_USERNAME_VERIFIED = 'FORM_GLOBAL_ACTION_TARGET_USERNAME_VERIFIED';
export const FORM_GLOBAL_ACTION_TARGET_USERNAME_UNVERIFIED = 'FORM_GLOBAL_ACTION_TARGET_USERNAME_UNVERIFIED';
