/* Application Constant */

// DOMAIN
export const DOMAIN_URL = "https://mbonus.asia";
// export const API_DOMAIN_URL = "https://api.mbonus.testspots.com";
export const API_DOMAIN_URL = "https://api.mbonus.asia";

// PASSPORT
export const GRANT_TYPE = 'password';
export const CLIENT_ID = '2';
// export const CLIENT_SECRET = 'd8xY6clKdzr8sZm7ZKhugzg9CdnLvRoE091YqmcC';
export const CLIENT_SECRET = 'Db4ogtVS1wvGoHGpIWydZ84i3oGJeqBTolE0d1Vj';

// APP
export const ASYNCTORAGE_APP_TNC = 'ASYNCTORAGE_APP_TNC';
export const ASYNCTORAGE_APP_SHOW_WELCOME = 'ASYNCTORAGE_APP_SHOW_WELCOME';
export const ASYNCTORAGE_APP_IMG_SLIDERS = 'ASYNCTORAGE_APP_IMG_SLIDERS';
export const ASYNCTORAGE_APP_CONTACT_US = 'ASYNCTORAGE_APP_CONTACT_US';
export const ASYNCTORAGE_APP_YOUTUBE_LINK = 'ASYNCTORAGE_APP_YOUTUBE_LINK';

// USER
export const ASYNCTORAGE_USER_TOKEN = 'ASYNCTORAGE_USER_TOKEN';
export const ASYNCTORAGE_USER_LAST_LOGIN = 'ASYNCTORAGE_USER_LAST_LOGIN';
export const ASYNCTORAGE_USER_DETAILS = 'ASYNCTORAGE_USER_DETAILS';
export const ASYNCTORAGE_USER_PREF_LANGUAGE = 'ASYNCTORAGE_USER_PREF_LANGUAGE';
export const ASYNCTORAGE_USER_BANK_REREFERENCE = 'ASYNCTORAGE_USER_BANK_REREFERENCE';
